name: script_lab
description: "Escritura de guiones de YouTube con IA local (Ollama)."
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.11.0

dependencies:
  diff_match_patch: ^0.4.1
  fetch_client: ^1.2.1
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  get: ^4.7.3
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  http: ^1.6.0
  intl: ^0.20.2
  pdf: ^3.12.0
  printing: ^5.14.3
  uuid: ^4.5.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.1
  build_runner: ^2.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf
