// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:script_lab/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AiSuggestionAdapter());
    registerAdapter(AppSettingsAdapter());
    registerAdapter(ChannelVariablesAdapter());
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(ProjectDefaultsAdapter());
    registerAdapter(ProjectStatusAdapter());
    registerAdapter(ProjectSuggestionAdapter());
    registerAdapter(PromptItemAdapter());
    registerAdapter(ScriptSectionAdapter());
    registerAdapter(ScriptVersionAdapter());
    registerAdapter(StructureAdapter());
    registerAdapter(StructureStepAdapter());
    registerAdapter(StyleSampleAdapter());
    registerAdapter(SuggestionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AiSuggestionAdapter());
    registerAdapter(AppSettingsAdapter());
    registerAdapter(ChannelVariablesAdapter());
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(ProjectDefaultsAdapter());
    registerAdapter(ProjectStatusAdapter());
    registerAdapter(ProjectSuggestionAdapter());
    registerAdapter(PromptItemAdapter());
    registerAdapter(ScriptSectionAdapter());
    registerAdapter(ScriptVersionAdapter());
    registerAdapter(StructureAdapter());
    registerAdapter(StructureStepAdapter());
    registerAdapter(StyleSampleAdapter());
    registerAdapter(SuggestionTypeAdapter());
  }
}
